CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Models/Medico.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public long IDMedico { get; set; }
        public string CRM { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Email { get; set; }
        public bool AtendePorConvenio { get; set; }
        public bool TemClinica { get; set; }
        public string WebsiteBlog { get; set; }
        public int IDCidade { get; set; }
        public int IDEspecialidade { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Especialidade Especialidade { get; set; }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Models/Medicos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicos
    {
        public long IDMedico { get; set; }
        public string CRM { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Email { get; set; }
        public bool AtendePorConvenio { get; set; }
        public bool TemClinica { get; set; }
        public string WebsiteBlog { get; set; }
        public int IDCidade { get; set; }
        public int IDEspecialidade { get; set; }
    
        public virtual Cidades Cidades { get; set; }
        public virtual Cidades Cidades1 { get; set; }
        public virtual Especialidades Especialidades { get; set; }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Data;
using System.Web.Mvc;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : BaseController
    {
        private EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();

        public ActionResult Index()
        {
            var medicos = db.Medicos.Include("Cidades").Include("Especialidades");
            return View(medicos);
        }

        public ActionResult Adicionar()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Medicos medico)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        public ActionResult Editar(long id)
        {
            Medicos medico = db.Medicos.Find(id);
            
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            
            return View(medico);
        }

        [HttpPost]
        public ActionResult Editar(Medicos medico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }

        [HttpPost]
        public string Excluir(long id)
        {
            try
            {
                Medicos medico = db.Medicos.Find(id);
                db.Medicos.Remove(medico);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Medicos/Adicionar.cshtml
@model CadeMeuMedico.Models.Medicos

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar novo Médico</h2>

@using (Html.BeginForm("Adicionar", "Medicos", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados do médico</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CRM)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CRM, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.CRM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            <label>Endereço</label>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Endereco, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Endereco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Bairro)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Bairro, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Email, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            <label>Atende por convênio</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AtendePorConvenio)
            @Html.ValidationMessageFor(model => model.AtendePorConvenio)
        </div>

        <div class="editor-label">
            <label>Tem clínica</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TemClinica)
            @Html.ValidationMessageFor(model => model.TemClinica)
        </div>

        <div class="editor-label">
            <label>Site</label>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.WebsiteBlog, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.WebsiteBlog)
        </div>

        <div class="editor-label">
            <label>Cidade</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("IDCidade", String.Empty)
            @Html.ValidationMessageFor(model => model.IDCidade)
        </div>

        <div class="editor-label">
            <label>Especialidade</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("IDEspecialidade", String.Empty)
            @Html.ValidationMessageFor(model => model.IDEspecialidade)
        </div>
        <br />
        <p>
            <input type="submit" class="btn btn-primary" value="Gravar" />
        </p>
    </fieldset>
}

@section Scripts{
    <script>
        $("#menuMedicos").addClass("active");
    </script>
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Medicos/Editar.cshtml
@model CadeMeuMedico.Models.Medicos

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Médico</h2>

@using (Html.BeginForm("Editar", "Medicos", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados do médico</legend>
        @Html.HiddenFor(model => model.IDMedico)
        <div class="editor-label">
            @Html.LabelFor(model => model.CRM)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CRM, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.CRM)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            <label>Endereço</label>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Endereco, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Endereco)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Bairro)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Bairro, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Bairro)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Email, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            <label>Atende por convênio</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AtendePorConvenio)
            @Html.ValidationMessageFor(model => model.AtendePorConvenio)
        </div>

        <div class="editor-label">
            <label>Tem clínica</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TemClinica)
            @Html.ValidationMessageFor(model => model.TemClinica)
        </div>

        <div class="editor-label">
            <label>Site</label>
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.WebsiteBlog, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.WebsiteBlog)
        </div>

        <div class="editor-label">
            <label>Cidade</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("IDCidade", String.Empty)
            @Html.ValidationMessageFor(model => model.IDCidade)
        </div>

        <div class="editor-label">
            <label>Especialidade</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("IDEspecialidade", String.Empty)
            @Html.ValidationMessageFor(model => model.IDEspecialidade)
        </div>
        <br />
        <p>
            <input type="submit" class="btn btn-primary" value="Gravar" />
        </p>
    </fieldset>
}

@section Scripts{
    <script>
        $("#menuMedicos").addClass("active");
    </script>
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Medicos/Index.cshtml
@model IEnumerable<CadeMeuMedico.Models.Medicos>

@{
    ViewBag.Title = "Médicos";
}

<h2>Médicos</h2>

<p>
    @Html.ActionLink("Adicionar novo médico", "Adicionar", null, new {@class = "btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            Cidade
        </th>
        <th>
            Especialidade
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDCidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDEspecialidade)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id=item.IDMedico }) |
                @Html.ActionLink("Excluir", "Excluir", new { id=item.IDMedico }, new {@class="excluir"})
            </td>
        </tr>
    }
</table>

@section Scripts{
    <script>
        $(function () {
            var linhaAtual;
            
            $("#menuMedicos").addClass("active");

            $(".excluir").on("click", function () {
                if (confirm("Confirma a exclusão do médico?")) {
                    var urlExclusao = $(this).attr("href");
                    linhaAtual = $(this).closest("tr");

                    $.ajax({
                        url: urlExclusao,
                        type: "POST"
                    }).done(function (excluiu) {
                        if (excluiu) {
                            linhaAtual.remove();
                        } else {
                            alert("Ocorreu algum problema na exclusão do médico :(");
                        }
                    }).fail(function () {
                        alert("Ocorreu algum erro :(");
                    });
                }

                return false;
            });
        });

    </script>
}