CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Models/Cidade.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Medicos = new HashSet<Medico>();
        }
    
        public int IDCidade { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Medico> Medicos { get; set; }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Models/Cidades.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidades
    {
        public Cidades()
        {
            this.Medicos = new HashSet<Medicos>();
            this.Medicos1 = new HashSet<Medicos>();
        }
    
        public int IDCidade { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Medicos> Medicos { get; set; }
        public virtual ICollection<Medicos> Medicos1 { get; set; }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Controllers/CidadesController.cs
using System;
using System.Data;
using System.Web.Mvc;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class CidadesController : BaseController
    {
        private EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();

        public ActionResult Index()
        {
            var cidades = db.Cidades;
            return View(cidades);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Cidades cidade)
        {
            if (ModelState.IsValid)
            {
                db.Cidades.Add(cidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cidade);
        }

        public ActionResult Editar(long id)
        {
            Cidades cidade = db.Cidades.Find(id);

            return View(cidade);
        }

        [HttpPost]
        public ActionResult Editar(Cidades cidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cidade);
        }

        [HttpPost]
        public string Excluir(long id)
        {
            try
            {
                Cidades cidade = db.Cidades.Find(id);
                db.Cidades.Remove(cidade);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Cidades/Adicionar.cshtml
@model CadeMeuMedico.Models.Cidades

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar Cidade</h2>

@using (Html.BeginForm("Adicionar", "Cidades", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados da cidade</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new{@class="form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" value="Gravar" class="btn btn-primary" />
        </p>
    </fieldset>
}

@section Scripts {
    <script>
        $("#menuCidades").addClass("active");
    </script>
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Cidades/Editar.cshtml
@model CadeMeuMedico.Models.Cidades

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Cidade</h2>

@using (Html.BeginForm("Editar", "Cidades", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados da cidade</legend>
        @Html.HiddenFor(model => model.IDCidade)
        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new{@class="form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" value="Gravar" class="btn btn-primary" />
        </p>
    </fieldset>
}

@section Scripts {
    <script>
        $("#menuCidades").addClass("active");
    </script>
}

CadeMeuMedico com MySQL/CadeMeuMedico/CadeMeuMedico/Views/Cidades/Index.cshtml
@model IEnumerable<CadeMeuMedico.Models.Cidades>

@{
    ViewBag.Title = "Cidades";
}

<h2>Cidades</h2>

<p>
    @Html.ActionLink("Adicionar nova cidade", "Adicionar", null, new {@class = "btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IDCidade }) |
            @Html.ActionLink("Excluir", "Excluir", new { id=item.IDCidade }, new {@class="excluir"})
        </td>
    </tr>
}

</table>

@section Scripts{
    <script>
        $(function () {
            var linhaAtual;

            $("#menuCidades").addClass("active");

            $(".excluir").on("click", function () {
                if (confirm("Confirma a exclusão da cidade?")) {
                    var urlExclusao = $(this).attr("href");
                    linhaAtual = $(this).closest("tr");

                    $.ajax({
                        url: urlExclusao,
                        type: "POST"
                    }).done(function (excluiu) {
                        if (excluiu) {
                            linhaAtual.remove();
                        } else {
                            alert("Ocorreu algum problema na exclusão da cidade :(, verifique se algum médico possui essa cidade.");
                        }
                    }).fail(function () {
                        alert("Ocorreu algum erro :(");
                    });
                }

                return false;
            });
        });

    </script>
}